# Card name mapping and metadata
# Maps internal/beta names to display names with rarity and character info

CARD_DATABASE = {
    # === IRONCLAD ===
    # Basic
    "Bash": {"display_name": "Bash", "rarity": "Basic", "character": "Ironclad", "type": "Attack"},
    "Defend": {"display_name": "Defend", "rarity": "Basic", "character": "Ironclad", "type": "Skill"},
    "Strike": {"display_name": "Strike", "rarity": "Basic", "character": "Ironclad", "type": "Attack"},

    # Common
    "Anger": {"display_name": "Anger", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Armaments": {"display_name": "Armaments", "rarity": "Common", "character": "Ironclad", "type": "Skill"},
    "Body Slam": {"display_name": "Body Slam", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Clash": {"display_name": "Clash", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Cleave": {"display_name": "Cleave", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Clothesline": {"display_name": "Clothesline", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Flex": {"display_name": "Flex", "rarity": "Common", "character": "Ironclad", "type": "Skill"},
    "Havoc": {"display_name": "Havoc", "rarity": "Common", "character": "Ironclad", "type": "Skill"},
    "Headbutt": {"display_name": "Headbutt", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Heavy Blade": {"display_name": "Heavy Blade", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Iron Wave": {"display_name": "Iron Wave", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Perfected Strike": {"display_name": "Perfected Strike", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Pommel Strike": {"display_name": "Pommel Strike", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Shrug It Off": {"display_name": "Shrug It Off", "rarity": "Common", "character": "Ironclad", "type": "Skill"},
    "Sword Boomerang": {"display_name": "Sword Boomerang", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Thunderclap": {"display_name": "Thunderclap", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "True Grit": {"display_name": "True Grit", "rarity": "Common", "character": "Ironclad", "type": "Skill"},
    "Twin Strike": {"display_name": "Twin Strike", "rarity": "Common", "character": "Ironclad", "type": "Attack"},
    "Warcry": {"display_name": "Warcry", "rarity": "Common", "character": "Ironclad", "type": "Skill"},
    "Wild Strike": {"display_name": "Wild Strike", "rarity": "Common", "character": "Ironclad", "type": "Attack"},

    # Uncommon
    "Battle Trance": {"display_name": "Battle Trance", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Blood for Blood": {"display_name": "Blood for Blood", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Bloodletting": {"display_name": "Bloodletting", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Burning Pact": {"display_name": "Burning Pact", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Carnage": {"display_name": "Carnage", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Combust": {"display_name": "Combust", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Dark Embrace": {"display_name": "Dark Embrace", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Disarm": {"display_name": "Disarm", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Dropkick": {"display_name": "Dropkick", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Dual Wield": {"display_name": "Dual Wield", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Entrench": {"display_name": "Entrench", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Evolve": {"display_name": "Evolve", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Feel No Pain": {"display_name": "Feel No Pain", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Fire Breathing": {"display_name": "Fire Breathing", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Flame Barrier": {"display_name": "Flame Barrier", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Ghostly Armor": {"display_name": "Ghostly Armor", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Hemokinesis": {"display_name": "Hemokinesis", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Infernal Blade": {"display_name": "Infernal Blade", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Inflame": {"display_name": "Inflame", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Intimidate": {"display_name": "Intimidate", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Metallicize": {"display_name": "Metallicize", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Power Through": {"display_name": "Power Through", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Pummel": {"display_name": "Pummel", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Rage": {"display_name": "Rage", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Rampage": {"display_name": "Rampage", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Reckless Charge": {"display_name": "Reckless Charge", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Rupture": {"display_name": "Rupture", "rarity": "Uncommon", "character": "Ironclad", "type": "Power"},
    "Searing Blow": {"display_name": "Searing Blow", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Second Wind": {"display_name": "Second Wind", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Seeing Red": {"display_name": "Seeing Red", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Sentinel": {"display_name": "Sentinel", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Sever Soul": {"display_name": "Sever Soul", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Shockwave": {"display_name": "Shockwave", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Spot Weakness": {"display_name": "Spot Weakness", "rarity": "Uncommon", "character": "Ironclad", "type": "Skill"},
    "Uppercut": {"display_name": "Uppercut", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},
    "Whirlwind": {"display_name": "Whirlwind", "rarity": "Uncommon", "character": "Ironclad", "type": "Attack"},

    # Rare
    "Barricade": {"display_name": "Barricade", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    "Berserk": {"display_name": "Berserk", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    "Bludgeon": {"display_name": "Bludgeon", "rarity": "Rare", "character": "Ironclad", "type": "Attack"},
    "Brutality": {"display_name": "Brutality", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    "Corruption": {"display_name": "Corruption", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    "Demon Form": {"display_name": "Demon Form", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    "Double Tap": {"display_name": "Double Tap", "rarity": "Rare", "character": "Ironclad", "type": "Skill"},
    "Exhume": {"display_name": "Exhume", "rarity": "Rare", "character": "Ironclad", "type": "Skill"},
    "Feed": {"display_name": "Feed", "rarity": "Rare", "character": "Ironclad", "type": "Attack"},
    "Fiend Fire": {"display_name": "Fiend Fire", "rarity": "Rare", "character": "Ironclad", "type": "Attack"},
    "Immolate": {"display_name": "Immolate", "rarity": "Rare", "character": "Ironclad", "type": "Attack"},
    "Impervious": {"display_name": "Impervious", "rarity": "Rare", "character": "Ironclad", "type": "Skill"},
    "Juggernaut": {"display_name": "Juggernaut", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    "Limit Break": {"display_name": "Limit Break", "rarity": "Rare", "character": "Ironclad", "type": "Skill"},
    "Offering": {"display_name": "Offering", "rarity": "Rare", "character": "Ironclad", "type": "Skill"},
    "Reaper": {"display_name": "Reaper", "rarity": "Rare", "character": "Ironclad", "type": "Attack"},

    # === SILENT ===
    # Basic
    "Neutralize": {"display_name": "Neutralize", "rarity": "Basic", "character": "Silent", "type": "Attack"},
    "Survivor": {"display_name": "Survivor", "rarity": "Basic", "character": "Silent", "type": "Skill"},

    # Common
    "Acrobatics": {"display_name": "Acrobatics", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Backflip": {"display_name": "Backflip", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Bane": {"display_name": "Bane", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Blade Dance": {"display_name": "Blade Dance", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Cloak And Dagger": {"display_name": "Cloak And Dagger", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Dagger Spray": {"display_name": "Dagger Spray", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Dagger Throw": {"display_name": "Dagger Throw", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Deadly Poison": {"display_name": "Deadly Poison", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Deflect": {"display_name": "Deflect", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Dodge and Roll": {"display_name": "Dodge and Roll", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Flying Knee": {"display_name": "Flying Knee", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Outmaneuver": {"display_name": "Outmaneuver", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "PiercingWail": {"display_name": "Piercing Wail", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Poisoned Stab": {"display_name": "Poisoned Stab", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Prepared": {"display_name": "Prepared", "rarity": "Common", "character": "Silent", "type": "Skill"},
    "Quick Slash": {"display_name": "Quick Slash", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Slice": {"display_name": "Slice", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Sucker Punch": {"display_name": "Sucker Punch", "rarity": "Common", "character": "Silent", "type": "Attack"},
    "Underhanded Strike": {"display_name": "Underhanded Strike", "rarity": "Common", "character": "Silent", "type": "Attack"},

    # Uncommon
    "All Out Attack": {"display_name": "All-Out Attack", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Backstab": {"display_name": "Backstab", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Blur": {"display_name": "Blur", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Bouncing Flask": {"display_name": "Bouncing Flask", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Calculated Gamble": {"display_name": "Calculated Gamble", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Caltrops": {"display_name": "Caltrops", "rarity": "Uncommon", "character": "Silent", "type": "Power"},
    "Catalyst": {"display_name": "Catalyst", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Choke": {"display_name": "Choke", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Concentrate": {"display_name": "Concentrate", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Crippling Poison": {"display_name": "Crippling Poison", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Dash": {"display_name": "Dash", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Distraction": {"display_name": "Distraction", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Endless Agony": {"display_name": "Endless Agony", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Escape Plan": {"display_name": "Escape Plan", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Eviscerate": {"display_name": "Eviscerate", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Expertise": {"display_name": "Expertise", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Finisher": {"display_name": "Finisher", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Flechettes": {"display_name": "Flechettes", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Footwork": {"display_name": "Footwork", "rarity": "Uncommon", "character": "Silent", "type": "Power"},
    "Heel Hook": {"display_name": "Heel Hook", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Infinite Blades": {"display_name": "Infinite Blades", "rarity": "Uncommon", "character": "Silent", "type": "Power"},
    "Leg Sweep": {"display_name": "Leg Sweep", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Masterful Stab": {"display_name": "Masterful Stab", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Noxious Fumes": {"display_name": "Noxious Fumes", "rarity": "Uncommon", "character": "Silent", "type": "Power"},
    "Predator": {"display_name": "Predator", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Reflex": {"display_name": "Reflex", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Riddle With Holes": {"display_name": "Riddle With Holes", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Setup": {"display_name": "Setup", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Skewer": {"display_name": "Skewer", "rarity": "Uncommon", "character": "Silent", "type": "Attack"},
    "Tactician": {"display_name": "Tactician", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Terror": {"display_name": "Terror", "rarity": "Uncommon", "character": "Silent", "type": "Skill"},
    "Well Laid Plans": {"display_name": "Well-Laid Plans", "rarity": "Uncommon", "character": "Silent", "type": "Power"},

    # Rare
    "A Thousand Cuts": {"display_name": "A Thousand Cuts", "rarity": "Rare", "character": "Silent", "type": "Power"},
    "Adrenaline": {"display_name": "Adrenaline", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "After Image": {"display_name": "After Image", "rarity": "Rare", "character": "Silent", "type": "Power"},
    "Alchemize": {"display_name": "Alchemize", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Bullet Time": {"display_name": "Bullet Time", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Burst": {"display_name": "Burst", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Corpse Explosion": {"display_name": "Corpse Explosion", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Die Die Die": {"display_name": "Die Die Die", "rarity": "Rare", "character": "Silent", "type": "Attack"},
    "Doppelganger": {"display_name": "Doppelganger", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Envenom": {"display_name": "Envenom", "rarity": "Rare", "character": "Silent", "type": "Power"},
    "Glass Knife": {"display_name": "Glass Knife", "rarity": "Rare", "character": "Silent", "type": "Attack"},
    "Grand Finale": {"display_name": "Grand Finale", "rarity": "Rare", "character": "Silent", "type": "Attack"},
    "Malaise": {"display_name": "Malaise", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Nightmare": {"display_name": "Nightmare", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Phantasmal Killer": {"display_name": "Phantasmal Killer", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Storm of Steel": {"display_name": "Storm of Steel", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Unload": {"display_name": "Unload", "rarity": "Rare", "character": "Silent", "type": "Attack"},
    "Wraith Form v2": {"display_name": "Wraith Form", "rarity": "Rare", "character": "Silent", "type": "Power"},

    # === DEFECT ===
    # Basic
    "Dualcast": {"display_name": "Dualcast", "rarity": "Basic", "character": "Defect", "type": "Skill"},
    "Zap": {"display_name": "Zap", "rarity": "Basic", "character": "Defect", "type": "Skill"},

    # Common
    "Ball Lightning": {"display_name": "Ball Lightning", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Barrage": {"display_name": "Barrage", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Beam Cell": {"display_name": "Beam Cell", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Charge Battery": {"display_name": "Charge Battery", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Chill": {"display_name": "Chill", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Cold Snap": {"display_name": "Cold Snap", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Compile Driver": {"display_name": "Compile Driver", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Coolheaded": {"display_name": "Coolheaded", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Gash": {"display_name": "Claw", "rarity": "Common", "character": "Defect", "type": "Attack"},  # BETA NAME
    "Go for the Eyes": {"display_name": "Go for the Eyes", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Hologram": {"display_name": "Hologram", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Leap": {"display_name": "Leap", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Rebound": {"display_name": "Rebound", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Recursion": {"display_name": "Recursion", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Stack": {"display_name": "Stack", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Steam": {"display_name": "Steam Barrier", "rarity": "Common", "character": "Defect", "type": "Skill"},
    "Streamline": {"display_name": "Streamline", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Sweeping Beam": {"display_name": "Sweeping Beam", "rarity": "Common", "character": "Defect", "type": "Attack"},

    # Uncommon
    "Aggregate": {"display_name": "Aggregate", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Auto Shields": {"display_name": "Auto-Shields", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Blizzard": {"display_name": "Blizzard", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "BootSequence": {"display_name": "Boot Sequence", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},  # INTERNAL NAME
    "Bullseye": {"display_name": "Bullseye", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Capacitor": {"display_name": "Capacitor", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Chaos": {"display_name": "Chaos", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Claw": {"display_name": "Claw", "rarity": "Common", "character": "Defect", "type": "Attack"},
    "Consume": {"display_name": "Consume", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Darkness": {"display_name": "Darkness", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Doom and Gloom": {"display_name": "Doom and Gloom", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Defragment": {"display_name": "Defragment", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Equilibrium": {"display_name": "Equilibrium", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "FTL": {"display_name": "FTL", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Fusion": {"display_name": "Fusion", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Genetic Algorithm": {"display_name": "Genetic Algorithm", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Glacier": {"display_name": "Glacier", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Heatsinks": {"display_name": "Heatsinks", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Hello World": {"display_name": "Hello World", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Loop": {"display_name": "Loop", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Melter": {"display_name": "Melter", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Recycle": {"display_name": "Recycle", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Reinforced Body": {"display_name": "Reinforced Body", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Reprogram": {"display_name": "Reprogram", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Rip and Tear": {"display_name": "Rip and Tear", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Scrape": {"display_name": "Scrape", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Self Repair": {"display_name": "Self Repair", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Skim": {"display_name": "Skim", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Static Discharge": {"display_name": "Static Discharge", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Steam Power": {"display_name": "Steam Power", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Storm": {"display_name": "Storm", "rarity": "Uncommon", "character": "Defect", "type": "Power"},
    "Sunder": {"display_name": "Sunder", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Tempest": {"display_name": "Tempest", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Thunder Strike": {"display_name": "Thunder Strike", "rarity": "Uncommon", "character": "Defect", "type": "Attack"},
    "Turbo": {"display_name": "Turbo", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Lockon": {"display_name": "Lockon", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},

    # Rare
    "All For One": {"display_name": "All For One", "rarity": "Rare", "character": "Defect", "type": "Attack"},
    "Amplify": {"display_name": "Amplify", "rarity": "Rare", "character": "Defect", "type": "Skill"},
    "Biased Cognition": {"display_name": "Biased Cognition", "rarity": "Rare", "character": "Defect", "type": "Power"},
    "Buffer": {"display_name": "Buffer", "rarity": "Rare", "character": "Defect", "type": "Power"},
    "Core Surge": {"display_name": "Core Surge", "rarity": "Rare", "character": "Defect", "type": "Attack"},
    "Creative AI": {"display_name": "Creative AI", "rarity": "Rare", "character": "Defect", "type": "Power"},
    "Echo Form": {"display_name": "Echo Form", "rarity": "Rare", "character": "Defect", "type": "Power"},
    "Electrodynamics": {"display_name": "Electrodynamics", "rarity": "Rare", "character": "Defect", "type": "Power"},
    "Fission": {"display_name": "Fission", "rarity": "Rare", "character": "Defect", "type": "Skill"},
    "Hyperbeam": {"display_name": "Hyperbeam", "rarity": "Rare", "character": "Defect", "type": "Attack"},
    "Machine Learning": {"display_name": "Machine Learning", "rarity": "Rare", "character": "Defect", "type": "Power"},
    "Meteor Strike": {"display_name": "Meteor Strike", "rarity": "Rare", "character": "Defect", "type": "Attack"},
    "Multi-Cast": {"display_name": "Multi-Cast", "rarity": "Rare", "character": "Defect", "type": "Skill"},
    "Rainbow": {"display_name": "Rainbow", "rarity": "Rare", "character": "Defect", "type": "Skill"},
    "Seek": {"display_name": "Seek", "rarity": "Rare", "character": "Defect", "type": "Skill"},
    "White Noise": {"display_name": "White Noise", "rarity": "Rare", "character": "Defect", "type": "Skill"},

    # === WATCHER ===
    # Basic
    "Eruption": {"display_name": "Eruption", "rarity": "Basic", "character": "Watcher", "type": "Attack"},
    "Vigilance": {"display_name": "Vigilance", "rarity": "Basic", "character": "Watcher", "type": "Skill"},

    # Common
    "BowlingBash": {"display_name": "Bowling Bash", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "Consecrate": {"display_name": "Consecrate", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "Crescendo": {"display_name": "Crescendo", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "CrushJoints": {"display_name": "Crush Joints", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "CutThroughFate": {"display_name": "Cut Through Fate", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "EmptyBody": {"display_name": "Empty Body", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "EmptyFist": {"display_name": "Empty Fist", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "Evaluate": {"display_name": "Evaluate", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "FlurryOfBlows": {"display_name": "Flurry of Blows", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "FollowUp": {"display_name": "Follow-Up", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "FlyingSleeves": {"display_name": "Flying Sleeves", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "Halt": {"display_name": "Halt", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "JustLucky": {"display_name": "Just Lucky", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "Prostrate": {"display_name": "Prostrate", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "Protect": {"display_name": "Protect", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "SashWhip": {"display_name": "Sash Whip", "rarity": "Common", "character": "Watcher", "type": "Attack"},
    "ThirdEye": {"display_name": "Third Eye", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "Tranquility": {"display_name": "Tranquility", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "Worship": {"display_name": "Worship", "rarity": "Common", "character": "Watcher", "type": "Skill"},

    # Uncommon
    "BattleHymn": {"display_name": "Battle Hymn", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "CarveReality": {"display_name": "Carve Reality", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Collect": {"display_name": "Collect", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Conclude": {"display_name": "Conclude", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Conjure Blade": {"display_name": "Conjure Blade", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "DeceiveReality": {"display_name": "Deceive Reality", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "EmptyMind": {"display_name": "Empty Mind", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Establishment": {"display_name": "Establishment", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "FearNoEvil": {"display_name": "Fear No Evil", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Foresight": {"display_name": "Foresight", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "Foreign Influence": {"display_name": "Foreign Influence", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Indignation": {"display_name": "Indignation", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "InnerPeace": {"display_name": "Inner Peace", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "LikeWater": {"display_name": "Like Water", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "Meditate": {"display_name": "Meditate", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Mental Fortress": {"display_name": "Mental Fortress", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "Nirvana": {"display_name": "Nirvana", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "Perseverance": {"display_name": "Perseverance", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Pray": {"display_name": "Pray", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Pressure Points": {"display_name": "Pressure Points", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "ReachHeaven": {"display_name": "Reach Heaven", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Rushdown": {"display_name": "Rushdown", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "Sanctity": {"display_name": "Sanctity", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "SignatureMove": {"display_name": "Signature Move", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Study": {"display_name": "Study", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Swivel": {"display_name": "Swivel", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Talk to the Hand": {"display_name": "Talk to the Hand", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Tantrum": {"display_name": "Tantrum", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "WaveOfTheHand": {"display_name": "Wave of the Hand", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Weave": {"display_name": "Weave", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "WheelKick": {"display_name": "Wheel Kick", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "WindmillStrike": {"display_name": "Windmill Strike", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
    "Worship": {"display_name": "Worship", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "WreathOfFlame": {"display_name": "Wreath of Flame", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},

    # Rare
    "Alpha": {"display_name": "Alpha", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Blasphemy": {"display_name": "Blasphemy", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Brilliance": {"display_name": "Brilliance", "rarity": "Rare", "character": "Watcher", "type": "Attack"},
    "ConjureBlade": {"display_name": "Conjure Blade", "rarity": "Uncommon", "character": "Watcher", "type": "Skill"},
    "Deva Form": {"display_name": "Deva Form", "rarity": "Rare", "character": "Watcher", "type": "Power"},
    "DeusExMachina": {"display_name": "Deus Ex Machina", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Establishment": {"display_name": "Establishment", "rarity": "Uncommon", "character": "Watcher", "type": "Power"},
    "Judgement": {"display_name": "Judgement", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Lesson Learned": {"display_name": "Lesson Learned", "rarity": "Rare", "character": "Watcher", "type": "Attack"},
    "MasterReality": {"display_name": "Master Reality", "rarity": "Rare", "character": "Watcher", "type": "Power"},
    "Omniscience": {"display_name": "Omniscience", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Ragnarok": {"display_name": "Ragnarok", "rarity": "Rare", "character": "Watcher", "type": "Attack"},
    "Scrawl": {"display_name": "Scrawl", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Spirit Shield": {"display_name": "Spirit Shield", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Vault": {"display_name": "Vault", "rarity": "Rare", "character": "Watcher", "type": "Skill"},
    "Wish": {"display_name": "Wish", "rarity": "Rare", "character": "Watcher", "type": "Skill"},

    # === COLORLESS ===
    "Apotheosis": {"display_name": "Apotheosis", "rarity": "Rare", "character": "Colorless", "type": "Skill"},
    "Bandage Up": {"display_name": "Bandage Up", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Blind": {"display_name": "Blind", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Chrysalis": {"display_name": "Chrysalis", "rarity": "Rare", "character": "Colorless", "type": "Skill"},
    "Dark Shackles": {"display_name": "Dark Shackles", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Deep Breath": {"display_name": "Deep Breath", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Discovery": {"display_name": "Discovery", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Dramatic Entrance": {"display_name": "Dramatic Entrance", "rarity": "Uncommon", "character": "Colorless", "type": "Attack"},
    "Enlightenment": {"display_name": "Enlightenment", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Finesse": {"display_name": "Finesse", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Flash of Steel": {"display_name": "Flash of Steel", "rarity": "Uncommon", "character": "Colorless", "type": "Attack"},
    "Forethought": {"display_name": "Forethought", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Good Instincts": {"display_name": "Good Instincts", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "HandOfGreed": {"display_name": "Hand of Greed", "rarity": "Rare", "character": "Colorless", "type": "Attack"},
    "Impatience": {"display_name": "Impatience", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Jack Of All Trades": {"display_name": "Jack Of All Trades", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Madness": {"display_name": "Madness", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Magnetism": {"display_name": "Magnetism", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Master of Strategy": {"display_name": "Master of Strategy", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Mayhem": {"display_name": "Mayhem", "rarity": "Uncommon", "character": "Colorless", "type": "Power"},
    "Metamorphosis": {"display_name": "Metamorphosis", "rarity": "Rare", "character": "Colorless", "type": "Skill"},
    "Mind Blast": {"display_name": "Mind Blast", "rarity": "Uncommon", "character": "Colorless", "type": "Attack"},
    "Panacea": {"display_name": "Panacea", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "PanicButton": {"display_name": "Panic Button", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Panache": {"display_name": "Panache", "rarity": "Uncommon", "character": "Colorless", "type": "Power"},
    "Purity": {"display_name": "Purity", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Secret Technique": {"display_name": "Secret Technique", "rarity": "Rare", "character": "Colorless", "type": "Skill"},
    "Secret Weapon": {"display_name": "Secret Weapon", "rarity": "Rare", "character": "Colorless", "type": "Attack"},
    "Swift Strike": {"display_name": "Swift Strike", "rarity": "Uncommon", "character": "Colorless", "type": "Attack"},
    "The Bomb": {"display_name": "The Bomb", "rarity": "Rare", "character": "Colorless", "type": "Skill"},
    "Thinking Ahead": {"display_name": "Thinking Ahead", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Transmutation": {"display_name": "Transmutation", "rarity": "Rare", "character": "Colorless", "type": "Skill"},
    "Trip": {"display_name": "Trip", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Violence": {"display_name": "Violence", "rarity": "Rare", "character": "Colorless", "type": "Skill"},

    # === CURSES ===
    "Ascender's Bane": {"display_name": "Ascender's Bane", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Clumsy": {"display_name": "Clumsy", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Decay": {"display_name": "Decay", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Doubt": {"display_name": "Doubt", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Injury": {"display_name": "Injury", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Necronomicurse": {"display_name": "Necronomicurse", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Normality": {"display_name": "Normality", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Pain": {"display_name": "Pain", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Parasite": {"display_name": "Parasite", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Regret": {"display_name": "Regret", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Shame": {"display_name": "Shame", "rarity": "Curse", "character": "Curse", "type": "Curse"},
    "Writhe": {"display_name": "Writhe", "rarity": "Curse", "character": "Curse", "type": "Curse"},

    # === STATUS ===
    "Burn": {"display_name": "Burn", "rarity": "Status", "character": "Status", "type": "Status"},
    "Dazed": {"display_name": "Dazed", "rarity": "Status", "character": "Status", "type": "Status"},
    "Slimed": {"display_name": "Slimed", "rarity": "Status", "character": "Status", "type": "Status"},
    "Void": {"display_name": "Void", "rarity": "Status", "character": "Status", "type": "Status"},
    "Wound": {"display_name": "Wound", "rarity": "Status", "character": "Status", "type": "Status"},

    # === SPECIAL ===
    "Beta": {"display_name": "Beta", "rarity": "Special", "character": "Defect", "type": "Skill"},
    "Expunger": {"display_name": "Expunger", "rarity": "Special", "character": "Silent", "type": "Attack"},
    "Insight": {"display_name": "Insight", "rarity": "Special", "character": "Watcher", "type": "Skill"},
    "Miracle": {"display_name": "Miracle", "rarity": "Special", "character": "Watcher", "type": "Skill"},
    "Safety": {"display_name": "Safety", "rarity": "Special", "character": "Colorless", "type": "Skill"},
    "Shiv": {"display_name": "Shiv", "rarity": "Special", "character": "Silent", "type": "Attack"},
    "Smite": {"display_name": "Smite", "rarity": "Special", "character": "Watcher", "type": "Attack"},
    "Through Violence": {"display_name": "Through Violence", "rarity": "Special", "character": "Watcher", "type": "Attack"},

    # Additional cards found in data
    "Accuracy": {"display_name": "Accuracy", "rarity": "Uncommon", "character": "Silent", "type": "Power"},
    "Alchemize": {"display_name": "Alchemize", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "ClearTheMind": {"display_name": "Clear the Mind", "rarity": "Common", "character": "Watcher", "type": "Skill"},
    "Conserve Battery": {"display_name": "Conserve Battery", "rarity": "Uncommon", "character": "Defect", "type": "Skill"},
    "Double Energy": {"display_name": "Double Energy", "rarity": "Uncommon", "character": "Colorless", "type": "Skill"},
    "Night Terror": {"display_name": "Night Terror", "rarity": "Special", "character": "Silent", "type": "Attack"},
    "Nightmare": {"display_name": "Nightmare", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "PathToVictory": {"display_name": "Path to Victory", "rarity": "Rare", "character": "Watcher", "type": "Attack"},
    "Sadistic Nature": {"display_name": "Sadistic Nature", "rarity": "Rare", "character": "Ironclad", "type": "Power"},
    # "Singing Bowl" is a relic that can appear as a card choice option - filtered out in backend
    "Venomology": {"display_name": "Venomology", "rarity": "Rare", "character": "Silent", "type": "Skill"},
    "Wallop": {"display_name": "Wallop", "rarity": "Uncommon", "character": "Watcher", "type": "Attack"},
}


def get_card_info(card_name):
    """Get display name and metadata for a card, handling beta/internal names"""
    # Strip upgrade suffix if present
    base_name = card_name
    is_upgraded = False
    if card_name.endswith('+1'):
        base_name = card_name[:-2]
        is_upgraded = True

    # Look up card info
    card_info = CARD_DATABASE.get(base_name, {
        "display_name": base_name,
        "rarity": "Unknown",
        "character": "Unknown",
        "type": "Unknown"
    })

    return {
        **card_info,
        "is_upgraded": is_upgraded
    }
